//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RfidCollections", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RfidCollections : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Empty_ptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZpltnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExidvField;
        
        private int Tag_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rfidKeyField;
        
        private int plantToField;
        
        private int stockLocToField;
        
        private int stockBinToField;
        
        private int plantFromField;
        
        private int stockLocFromField;
        
        private int stockBinFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string assLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string linePointField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Empty_pt {
            get {
                return this.Empty_ptField;
            }
            set {
                if ((object.ReferenceEquals(this.Empty_ptField, value) != true)) {
                    this.Empty_ptField = value;
                    this.RaisePropertyChanged("Empty_pt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Action {
            get {
                return this.ActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionField, value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Zpltn {
            get {
                return this.ZpltnField;
            }
            set {
                if ((object.ReferenceEquals(this.ZpltnField, value) != true)) {
                    this.ZpltnField = value;
                    this.RaisePropertyChanged("Zpltn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Matnr {
            get {
                return this.MatnrField;
            }
            set {
                if ((object.ReferenceEquals(this.MatnrField, value) != true)) {
                    this.MatnrField = value;
                    this.RaisePropertyChanged("Matnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Exidv {
            get {
                return this.ExidvField;
            }
            set {
                if ((object.ReferenceEquals(this.ExidvField, value) != true)) {
                    this.ExidvField = value;
                    this.RaisePropertyChanged("Exidv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Tag_id {
            get {
                return this.Tag_idField;
            }
            set {
                if ((this.Tag_idField.Equals(value) != true)) {
                    this.Tag_idField = value;
                    this.RaisePropertyChanged("Tag_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string rfidKey {
            get {
                return this.rfidKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.rfidKeyField, value) != true)) {
                    this.rfidKeyField = value;
                    this.RaisePropertyChanged("rfidKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int plantTo {
            get {
                return this.plantToField;
            }
            set {
                if ((this.plantToField.Equals(value) != true)) {
                    this.plantToField = value;
                    this.RaisePropertyChanged("plantTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int stockLocTo {
            get {
                return this.stockLocToField;
            }
            set {
                if ((this.stockLocToField.Equals(value) != true)) {
                    this.stockLocToField = value;
                    this.RaisePropertyChanged("stockLocTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int stockBinTo {
            get {
                return this.stockBinToField;
            }
            set {
                if ((this.stockBinToField.Equals(value) != true)) {
                    this.stockBinToField = value;
                    this.RaisePropertyChanged("stockBinTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int plantFrom {
            get {
                return this.plantFromField;
            }
            set {
                if ((this.plantFromField.Equals(value) != true)) {
                    this.plantFromField = value;
                    this.RaisePropertyChanged("plantFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int stockLocFrom {
            get {
                return this.stockLocFromField;
            }
            set {
                if ((this.stockLocFromField.Equals(value) != true)) {
                    this.stockLocFromField = value;
                    this.RaisePropertyChanged("stockLocFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int stockBinFrom {
            get {
                return this.stockBinFromField;
            }
            set {
                if ((this.stockBinFromField.Equals(value) != true)) {
                    this.stockBinFromField = value;
                    this.RaisePropertyChanged("stockBinFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string assLine {
            get {
                return this.assLineField;
            }
            set {
                if ((object.ReferenceEquals(this.assLineField, value) != true)) {
                    this.assLineField = value;
                    this.RaisePropertyChanged("assLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string linePoint {
            get {
                return this.linePointField;
            }
            set {
                if ((object.ReferenceEquals(this.linePointField, value) != true)) {
                    this.linePointField = value;
                    this.RaisePropertyChanged("linePoint");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerMessage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ServerMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Msg {
            get {
                return this.MsgField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgField, value) != true)) {
                    this.MsgField = value;
                    this.RaisePropertyChanged("Msg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.DataInteractionSoap")]
    public interface DataInteractionSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 data 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataMethod", ReplyAction="*")]
        UnitTestProject.ServiceReference1.DataMethodResponse DataMethod(UnitTestProject.ServiceReference1.DataMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestProject.ServiceReference1.DataMethodResponse> DataMethodAsync(UnitTestProject.ServiceReference1.DataMethodRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DataMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DataMethod", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProject.ServiceReference1.DataMethodRequestBody Body;
        
        public DataMethodRequest() {
        }
        
        public DataMethodRequest(UnitTestProject.ServiceReference1.DataMethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DataMethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UnitTestProject.ServiceReference1.RfidCollections data;
        
        public DataMethodRequestBody() {
        }
        
        public DataMethodRequestBody(UnitTestProject.ServiceReference1.RfidCollections data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DataMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DataMethodResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProject.ServiceReference1.DataMethodResponseBody Body;
        
        public DataMethodResponse() {
        }
        
        public DataMethodResponse(UnitTestProject.ServiceReference1.DataMethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DataMethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UnitTestProject.ServiceReference1.ServerMessage DataMethodResult;
        
        public DataMethodResponseBody() {
        }
        
        public DataMethodResponseBody(UnitTestProject.ServiceReference1.ServerMessage DataMethodResult) {
            this.DataMethodResult = DataMethodResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataInteractionSoapChannel : UnitTestProject.ServiceReference1.DataInteractionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataInteractionSoapClient : System.ServiceModel.ClientBase<UnitTestProject.ServiceReference1.DataInteractionSoap>, UnitTestProject.ServiceReference1.DataInteractionSoap {
        
        public DataInteractionSoapClient() {
        }
        
        public DataInteractionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataInteractionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataInteractionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataInteractionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestProject.ServiceReference1.DataMethodResponse UnitTestProject.ServiceReference1.DataInteractionSoap.DataMethod(UnitTestProject.ServiceReference1.DataMethodRequest request) {
            return base.Channel.DataMethod(request);
        }
        
        public UnitTestProject.ServiceReference1.ServerMessage DataMethod(UnitTestProject.ServiceReference1.RfidCollections data) {
            UnitTestProject.ServiceReference1.DataMethodRequest inValue = new UnitTestProject.ServiceReference1.DataMethodRequest();
            inValue.Body = new UnitTestProject.ServiceReference1.DataMethodRequestBody();
            inValue.Body.data = data;
            UnitTestProject.ServiceReference1.DataMethodResponse retVal = ((UnitTestProject.ServiceReference1.DataInteractionSoap)(this)).DataMethod(inValue);
            return retVal.Body.DataMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestProject.ServiceReference1.DataMethodResponse> UnitTestProject.ServiceReference1.DataInteractionSoap.DataMethodAsync(UnitTestProject.ServiceReference1.DataMethodRequest request) {
            return base.Channel.DataMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject.ServiceReference1.DataMethodResponse> DataMethodAsync(UnitTestProject.ServiceReference1.RfidCollections data) {
            UnitTestProject.ServiceReference1.DataMethodRequest inValue = new UnitTestProject.ServiceReference1.DataMethodRequest();
            inValue.Body = new UnitTestProject.ServiceReference1.DataMethodRequestBody();
            inValue.Body.data = data;
            return ((UnitTestProject.ServiceReference1.DataInteractionSoap)(this)).DataMethodAsync(inValue);
        }
    }
}
